services:
  - type: web
    name: wayne-security
    env: python
    rootDir: backend
    buildCommand: >
      python -m pip install -r requirements.txt &&
      echo "== pip, python version ==" &&
      python -V &&
      python -m pip --version &&
      echo "== pip list (top) ==" &&
      python -m pip list --format=columns | head -n 30 &&
      echo "== where gunicorn (if any) ==" &&
      which gunicorn || python -m pip show gunicorn
startCommand: gunicorn app:create_app --bind 0.0.0.0:$PORTT
